name: Auto doc

on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install package
        run: pip install -r doc_generator/requirements.txt

      - name: Generate doc
        run: sphinx-build doc_generator/source docs
